# Generated by Django 3.1.7 on 2021-02-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modern',
            table='modern',
        ),
    ]
