# Generated by Django 3.1.7 on 2021-02-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210225_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern',
            name='text_f',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
